# Generated by Django 5.1.3 on 2024-11-14 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_mention'),
        ('usermanagement', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='uploaded_at',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='uploaded_at',
            new_name='uploadedAt',
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reactioType', models.CharField(choices=[('like', 'Like'), ('love', 'Love'), ('haha', 'Haha'), ('sad', 'Sad'), ('angry', 'Angry')], default='like', max_length=5)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='post.post')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='usermanagement.profile')),
            ],
        ),
    ]
