# Generated by Django 5.1.3 on 2024-11-14 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_rename_uploaded_at_comment_createdat_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reaction',
            old_name='reactioType',
            new_name='reactionType',
        ),
    ]
