# Generated by Django 5.1.3 on 2024-11-16 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_rename_reactiotype_reaction_reactiontype'),
        ('usermanagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=100)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('isRead', models.BooleanField(default=False)),
                ('receive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_notifications', to='usermanagement.profile')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications', to='usermanagement.profile')),
            ],
            options={
                'ordering': ['-createdAt'],
            },
        ),
    ]
