# Generated by Django 5.1.3 on 2024-11-16 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_comment_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='createdAt',
            new_name='uploadedAt',
        ),
    ]
