# Generated by Django 5.1.3 on 2024-11-18 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_story'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-uploadedAt']},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-uploadedAt']},
        ),
        migrations.AlterModelOptions(
            name='reaction',
            options={'ordering': ['-createdAt']},
        ),
        migrations.AlterModelOptions(
            name='story',
            options={'ordering': ['-createdAt']},
        ),
    ]
